documentation:
  - changed-files:
      - any-glob-to-any-file: "**/*.md"
  - changed-files:
      - any-glob-to-any-file: "README.md"

codeing:
  - changed-files:
      - any-glob-to-any-file: "config/index.ts"

dependencies:
  - changed-files:
      - any-glob-to-any-file: "package.json"
  - changed-files:
      - any-glob-to-any-file: "package-lock.json"

configuration:
  - changed-files:
      - any-glob-to-any-file: "*config/**"
  - changed-files:
      - any-glob-to-any-file: "tsconfig.json"

workflow:
  - changed-files:
      - any-glob-to-any-file: ".github/workflows/**"
